buytogether/buytogether/urls.py
"""buytogether URL Configuration

The `urlpatterns` list routes URLs to account_views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Functionaccount_views
    1. Add an import:  from my_app importaccount_views
    2. Add a URL to urlpatterns:  url(r'^$', account_views.home, name='home')
Class-basedaccount_views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from accounts import views as account_views
from accounts.auth_views import login_view, LogoutView
from buys import views as buy_views
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers

router = routers.DefaultRouter()

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^home/', account_views.welcome, name='welcome'),
    url(r'^tester/', account_views.trystuff),
    url(r'^contact/', account_views.contact, name='contact'),

    # Accounts URLs
    url(r'^accounts/login/', login_view, name='login'),
    url(r'^accounts/logout/', LogoutView.as_view(), name='logout'),

    url(r'^accounts/newuser/', account_views.MemberCreateView.as_view(), name='new_user'),
    url(r'^accounts/memberhome/', account_views.member_home, name='member_home'),

    url(r'^accounts/newclub/', account_views.create_club, name='new_club'),
    url(r'^accounts/(?P<slug>[a-z\-]+)/$', account_views.club_profile, name='club_profile'),
    url(r'^accounts/(?P<slug>[a-z\-]+)/manage/', account_views.manage_club, name='manage_club'),
    url(r'^accounts/club/join/', account_views.join_club, name='join'),
    url(r'^accounts/club/unjoin/', account_views.leave_club, name='unjoin'),

    # Buys URLs
    url(r'^buys/(?P<slug>[a-z\-]+)/addbuy/', buy_views.create_buy, name='add_buy'),
    url(r'^buys/(?P<pk>\d+)/manage/', buy_views.manage_buy, name='manage_buy'),
    url(r'^buys/(?P<pk>\d+)/add/', buy_views.add_to_buy, name='add_to_buy'),
    url(r'^buys/(?P<pk>\d+)/update/$', buy_views.update_buy, name='update_buy'),

    url(r'^buys/(?P<pk>\d+)/member_order/', buy_views.member_order_status, name='member_order_status'),
    url(r'^buys/orderform/create/', buy_views.add_item, name='add_item'),
    url(r'^buys/invoice/(?P<buy_pk>\d+)/(?P<member_pk>\d+)', buy_views.invoice, name='invoice'),

    # Boilerplate REST urls
    url(r'^api/v1/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

buytogether/buys/models.py
from django.db import models


class Buy(models.Model):
    STATUS_OPTIONS = {
        ('PD', 'Pending'),
        ('OP', 'Open'),
        ('CL', 'Closed'),
        ('FN', 'Finished'),
    }

    name = models.CharField(max_length=100)
    club = models.ForeignKey('accounts.Club', related_name='buys', blank=True)
    status = models.CharField(max_length=2, choices=STATUS_OPTIONS, default='OP')
    date_open = models.DateTimeField(auto_now=False)
    date_close = models.DateTimeField(auto_now=False)
    notes = models.TextField(max_length=1000, null=True, blank=True)
    order_min_dollar = models.FloatField(null=True, blank=True)
    order_min_weight = models.FloatField(null=True, blank=True)
    order_max_weight = models.FloatField(null=True, blank=True)
    order_weight_unit = models.CharField(max_length=10, null=True, blank=True)

    def order_total(self):
        """ The dollar value of all orders for every Product on This Buy """
        products = Product.objects.filter(buy=self)
        total = sum(p.order_total() for p in products)
        return total

    def __str__(self):
        return self.name

    def __repr__(self):
        return 'Buy object: {}, in Club: {}'.format(self.name, self.club)


class Product(models.Model):
    name = models.CharField(max_length=200, blank=True)
    buy = models.ForeignKey(Buy, related_name='products', blank=True, null=False)
    members = models.ManyToManyField('accounts.Member', related_name='products', blank=True)
    item_id = models.CharField(max_length=50, null=True, blank=True)
    description = models.CharField(max_length=1000, null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    origin = models.CharField(max_length=100, null=True, blank=True)
    unit = models.CharField(max_length=10, null=True, blank=True)
    unit_price = models.DecimalField(decimal_places=2, max_digits=8, null=True, blank=True)
    case_price = models.DecimalField(decimal_places=2, max_digits=8, null=True, blank=True)
    weight = models.FloatField(null=True, blank=True)
    weight_unit = models.FloatField(null=True, blank=True)
    order_min = models.FloatField(null=True, blank=True)

    def order_total(self):
        """ The dollar value of all orders for this Products on This Buy """
        memberorders = MemberOrder.objects.filter(order=self)
        total = sum(mo.order_total() for mo in memberorders)
        return total

    def order_count(self):
        """ The unit count of all orders for this Products on This Buy """
        memberorders = MemberOrder.objects.filter(order=self)
        total = sum(mo.order_quantity for mo in memberorders)
        return total

    def __str__(self):
        return self.name

    def __repr__(self):
        return 'Product object: {} in Buy: {}'.format(self.name, self.buy)


class MemberOrder(models.Model):
    """ Through model for Product and accounts.Member """

    member = models.ForeignKey('accounts.Member')
    order = models.ForeignKey(Product)

    order_quantity = models.DecimalField(decimal_places=2, max_digits=8, default=0)
    order_date = models.DateTimeField(auto_now=True)

    def order_total(self):
        """ The total cost of this MemberOrder """
        total = self.order.unit_price * self.order_quantity
        return total

    def __add__(self, other):
        return self.order_total() + other.order_total()

    def __radd__(self, other):
        return self.order_total() + other

    def __str__(self):
        return 'Member: {}, Product: {}, Quantity: {}'.format(self.member, self.order, self.order_quantity)

    def __repr__(self):
        return 'MemberOrder object for Member: {}, Product: {}'.format(self.member, self.order)

buytogether/templates/pages/buy_creation.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}


{% block main %}

    <h2>Create a New Buy</h2>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form action="" method="POST">
        {% csrf_token %}

        {% bootstrap_field form.name %}
        <p>Date format: yyyy-mm-dd</p>
        {% bootstrap_field form.date_open field_class='datepicker' %}
        {% bootstrap_field form.date_close field_class='datepicker' %}
        {% bootstrap_field form.notes %}

        <button>Submit</button>
    </form>

{% endblock %}

buytogether/templates/pages/buy_management.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block main %}

    <h2>{{ buy.name }}</h2>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    

    <h4><p>Club: <a href="/accounts/{{ buy.club.slug }}/manage/">{{ buy.club.name }}</a></p></h4>

    <h3>Orders on this Buy:</h3>

    <table>
        <thead>
        <tr>
            <th>Product Name</th>
            <th>Product ID</th>
            <th>Total Units Ordered</th>
            <th>Unit</th>
            <th>Total</th>
        </tr>
        </thead>
        <tbody>
        {% for p in buy.products.all %}
            <tr>
                <td>{{ p.name }}</td>
                <td>{{ p.item_id }}</td>
                <td>{{ p.order_count }}</td>
                <td>{{ p.unit }}</td>
                <td>${{ p.order_total|floatformat:2 }}</td>
            </tr>
        {% endfor %}
        </tbody>

        <tfoot>
        <tr>
            <td class='table_total' colspan="4">Order total:</td>
            <td>${{ buy.order_total|floatformat:2 }}</td>
        </tr>
        </tfoot>


    </table>



    <h3>Add products to this Buy:</h3>

    <form action="/buys/{{ buy.pk }}/add/" method="POST">
        {% csrf_token %}


        <table>
            <thead>
            <tr>
                <th>Product Name</th>
                <th>Product ID</th>
                <th>Unit Price</th>
                <th>Unit</th>
            </tr>
            </thead>

            {% for f in formset %}
                {{ f.id }}
                {{ f.errors }}

                <tr class="formset_row">
                    <td class="formset_field">
                        {% if f.instance.pk %}{{ f.DELETE }}{% endif %}
                        {% bootstrap_field f.name layout='horizontal' show_label=False %}
                    </td>
                    <td class="formset_field">{% bootstrap_field f.item_id layout='horizontal' show_label=False %}</td>
                    <td class="formset_field">{% bootstrap_field f.unit_price layout='horizontal' show_label=False %}</td>
                    <td class="formset_field">{% bootstrap_field f.unit layout='horizontal' show_label=False %}</td>
                </tr>
            {% endfor %}
        </table>

        {% buttons submit='Save' reset="Cancel" %}{% endbuttons %}
        {{ formset.management_form }}
    </form>

    <h3>Update Buy Information:</h3>

    <h5>Buy Name: {{ buy.name }}</h5>

    <form action="/buys/{{ buy.pk }}/update/" method="POST">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button>Update</button>
    </form>


{% endblock %}

{% block extra_javascript %}

    <script src="{% static 'formset.js' %}"></script>

    <script>
        $('.formset_row').formset({
            addText: 'add link',
            deleteText: 'remove',
            prefix: '{{ formset.prefix }}'
        });
    </script>
{% endblock %}

buytogether/templates/pages/club_management.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block main %}

    <h1>Club management</h1>

    <a href="../"><h4>Public profile</h4></a>

    <hr>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <table>

        <thead>
        <tr>
            <th>Name</th>
            <th>Email address</th>
            <th>Zip Code</th>
        </tr>
        </thead>

        <tbody>

        <h3>Members</h3>
        {% for m in members %}
            <tr>
                <td>{{ m.member.name_of_use }}</td>
                <td>{{ m.member.username }}</td>
                <td>{{ m.member.zip_code }}</td>
            </tr>
        {% endfor %}
        </tbody>

    </table>

    <hr>

    <h3>Buys</h3>

    <a href="/buys/{{ club.slug }}/addbuy/">
        <button>Create a New Buy</button>
    </a>

    {% for b in buys %}
        <table>
            <tr>
                <td><a href="/buys/{{ b.pk }}/manage/">{{ b.name }}</a></td>
                <td>{{ b.date_close }}</td>
            </tr>
        </table>
    {% endfor %}


    <hr>
    <h3>Update Club Information</h3>

    <h5>Club Name: {{ club.name }}</h5>

    <form action="" method="POST">
        {% csrf_token %}

        {% bootstrap_form form %}

        <button>Update</button>
    </form>

{% endblock %}

buytogether/templates/pages/club_profile.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block main %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <h1>{{ club.name }}</h1>

    {% if status %}

        {# Create button link to management page for managers only #}
        {% if status == 'manage' %}
            <a href="manage/">
                <button id="{{ status }}">{{ button }}</button>
            </a>

        {# Use button to join or leave club depending on currentstatus #}
        {% else %}
            <a>
                <button id="{{ status }}">{{ button }}</button>
            </a>

            <div style='display: none' id="dialog-confirm" title="Leave club?">
                <p><span class="ui-icon ui-icon-alert" style="float:left; margin:12px 12px 20px 0;"></span>This will
                    remove
                    you from the club. Are you sure?</p>
            </div>
        {% endif %}
    {% endif %}

    <h5>Owned by: {{ owner.member.name_of_use }}</h5>

    {# Display club info #}
    {% if club.desc_brief %}
        <h3>{{ club.desc_brief }}</h3>
    {% endif %}

    {% if club.desc_verbose %}
        <h4>Description:</h4>
        <p>{{ club.desc_verbose }}</p>
    {% endif %}

    {% if club.requirements %}
        <h4>Membership Requirements:</h4>
        <p>{{ club.requirements }}</p>
    {% endif %}


    {# Display club members in a table #}
    <table>
        <thead>
        <tr>
            <th>Member name</th>
            <th>Status</th>
            <th>Member Location</th>
        </tr>
        </thead>

        <tbody>
        {% for m in memberships %}
            <tr>
                <td>{{ m.member.name_of_use }}</td>
                <td>{{ m.get_status_display }}</td>
                <td>{{ m.member.zip_code }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h3>Currently open Buys:</h3>

    {% for b in buys %}
        <a href="/buys/{{ b.pk }}/member_order"><h4>{{ b.name }}</h4></a>

    {% endfor %}

{% endblock %}


{% block extra_javascript %}

    <script>
        "use strict";


        $('#join_club').click(function (evt) {
                evt.preventDefault();

                $.ajax({
                    url: '/accounts/club/join/',         // Target Server
                    type: 'POST',                        // Request Verb
                    data: {'slug': '{{club.slug}}'},     // Request Params
                    success: function (rsp) {            // Success Handler
                        $('#join_club').text(rsp.results);
                    },
                    error: function (err) {              // Error Handler
                        console.log(err);
                    }
                });

            }
        );


        $('#unjoin').click(function (evt) {
                evt.preventDefault();

                $(function () {
                    $("#dialog-confirm").dialog({
                        resizable: false,
                        height: "auto",
                        width: 400,
                        modal: true,
                        buttons: {
                            "Leave club": function () {
                                $(this).dialog("close");
                            },
                            Cancel: function () {
                                $(this).dialog("close");
                            }
                        }
                    });
                });


                $.ajax({
                    url: '/accounts/club/unjoin/',
                    type: 'POST',
                    data: {'slug': '{{club.slug}}'},
                    success: function (rsp) {
                        $('#unjoin').text(rsp.results);
                    },
                    error: function (err) {
                        console.log(err);
                    }
                });

            }
        );


    </script>

{% endblock %}

buytogether/templates/pages/clubcreation.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block main %}

    <h2>Create a New Club</h2>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form action="" method="POST">
        {% csrf_token %}

        {% bootstrap_form form %}

        <button>Create my Club</button>
    </form>

{% endblock %}

buytogether/templates/pages/contact.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block main %}

    <h4>BuyTogether is a project under development.</h4>
    <p>Please contact burrowingdan@gmail.com for support, or with bug reports, feature requests, or questions.</p>

{% endblock %}

buytogether/templates/pages/invoice.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block main %}

    <h3>{{ member.name_of_use }}'s order for <a href="/buys/{{ buy.pk }}/member_order/">{{ buy }}</a></h3>
    <h4>Club: {{ buy.club.name }}</h4>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <table border="solid">

        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Unit Price</th>
            <th>Unit</th>
            <th>Total</th>
        </tr>

        {% for o in orders %}
            <tr>
                <td>{{ o.order.name }}</td>
                <td>{{ o.order_quantity }}</td>
                <td>${{ o.order.unit_price|floatformat:2 }}</td>
                <td>{{ o.order.unit }}</td>
                <td>${{ o.order_total|floatformat:2 }}</td>
            </tr>
        {% endfor %}
        <tr>
            <td colspan="4">Invoice Total:</td>
            <td>${{ invoice_total|floatformat:2 }}</td>
        </tr>
    </table>

{% endblock %}

buytogether/templates/pages/join_buy.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}


{% block main %}

    <h3>
        {{ request.user.name_of_use }}'s orders on {{ buy.name }} in
        <a href="/accounts/{{ buy.club.slug }}/">{{ buy.club.name }}</a>
    </h3>

    <p>{{ buy.notes }}</p>

    <a href="/buys/invoice/{{ buy.pk }}/{{ request.user.pk }}"><button>View Invoice</button></a>

        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>

    <table>
        <thead>
        <tr>
            <th>Product Name</th>
            <th>Product ID</th>
            <th>Unit Price</th>
            <th>Order Quantity</th>
            <th>Unit</th>
        </tr>
        </thead>

        <tbody>
        <form action="" method="POST">
            {% csrf_token %}
            {% for form in formset %}
                {{ form.id }}
                {{ form.errors }}
                <tr>
                    <td>{{ form.instance.order.name }}</td>
                    <td>{{ form.instance.order.item_id }}</td>
                    <td>{{ form.instance.order.unit_price }}</td>
                    <td><input class="quantity_form" type="text" name="update_order_{{ form.instance.pk }}"
                               value="{{ form.instance.order_quantity }}" data-product="{{ form.instance.order.pk }}">
                    </td>
                    <td>{{ form.instance.order.unit }}</td>
                </tr>
            {% endfor %}
            {{ formset.management_form }}

        </form>


        <form action="" method="POST">
            {% csrf_token %}
            <fieldset name="memberless_products">
                {% for p in products %}
                    <tr>
                        <td>{{ p.name }}</td>
                        <td>{{ p.item_id }}</td>
                        <td>{{ p.unit_price }}</td>
                        <td><input class="quantity_form" name='new_order_{{ p.pk }}' type="text"
                                   placeholder="0" data-product="{{ p.pk }}">
                        </td>
                        <td>{{ p.unit }}</td>
                    </tr>
                {% endfor %}
            </fieldset>

        </form>
        </tbody>
    </table>


{% endblock %}

{% block extra_javascript %}

    <script type="text/javascript" src="{% static 'join_buy.js' %}"></script>

{% endblock %}

buytogether/templates/pages/login.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block main %}

    <form action="" method="POST">
    {% csrf_token %}

    {% bootstrap_form form %}

    <button>Submit</button>
    </form>


{% endblock %}

buytogether/templates/pages/membercreation.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block main %}

    <h2>Create a new BuyTogether user account</h2>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form action="" method="POST">
        {% csrf_token %}

        {% bootstrap_form form exclude='username' %}

        <button>Submit</button>
    </form>


{% endblock %}

buytogether/templates/pages/memberhome.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block main %}

    <h1>{{ request.user.name_of_use }}'s Dashboard</h1>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <a href="/accounts/newclub/">
        <button>Create New Club</button>
    </a>


    {# Show membership if there is memberships, display alt message if not #}
    {% if memberships %}

        <h2>My clubs</h2>
        {% for membership in memberships %}
            <a href="/accounts/{{ membership.club.slug }}">{{ membership.club.name }}</a><br>
            Membership Status: {{ membership.get_status_display }}
            <p><strong>{{ membership.club.desc_brief }}</strong></p><br>
        {% endfor %}

    {% else %}

        <h3>You're not in any Clubs. Start by finding one to join, or make your own.</h3>

    {% endif %}

{% endblock %}

buytogether/templates/pages/welcome.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block main %}

    <h3>BuyTogether helps you buy, together</h3>

    <p>BuyTogether is an app that aims to help groups of friends organize whole purchasing coops and buying clubs.
        BuyTogether can help you start a club, organizer your members, open buys to your members, and view member
    invoices. Save more, in less time, when you BuyTogether.</p>

    <p>Get starting by signing up, staring a club, and sharing your club's URL with friends.</p>

{% endblock %}